server:
  port: 8088
  servlet:
    context-path: /profile


spring:
  main:
    banner-mode: off
  application:
    name: profile-service
  datasource:
    url: ${env.SQL_URL}
    username: ${env.SQL_USER}
    password: ${env.SQL_PASSWORD}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${env.URL_BOOTSTRAP}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: >
        org.apache.kafka.common.security.scram.ScramLoginModule required
        username="g18ecommerce"
        password="I2g71o0eI1RulwK4Z3zC7LEaKqL5WY";
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
