GET http://localhost:3500/api/products?page=2&limit=5&category=Clothes

###
GET https://product-service-oj26.onrender.com/api/products/681864006b9150b157a9810a

###
DELETE http://localhost:3500/api/products/67c5cca05d4a4541999918eb


### 
POST http://localhost:3500/api/products
Content-Type: application/json

{
  "name": "Cotton Graphic Tee",
  "description": "A comfortable cotton t-shirt with a trendy graphic print.",
  "price": 19.99,
  "category": "Clothes",
  "attribute": {
    "brand": "TrendyWear",
    "description": "Soft and breathable fabric.",
    "isActive": true,
    "material": "Cotton",
    "size": ["S", "M", "L"],
    "color": ["Black", "White"],
    "pattern": ["Graphic"]
  },
  "images": ["https://loremflickr.com/640/480/fashion"],
  "thumbnailImage": "https://loremflickr.com/200/200/fashion",
  "ratings": {
    "average": 4.5,
    "count": 120
  },
  "isActive": true,
  "tags": ["casual", "cotton"]
}