@url = http://localhost:3500/api/products
@token = Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJHMTggRWNvbW1lcmNlIiwic3ViIjoidmllcXVlIiwiZXhwIjoxNzQ3OTEyNjg1LCJpYXQiOjE3NDc5MDkwODUsImp0aSI6ImUwNmJmNjBkLTJjODUtNDMyYi04ZTljLTY5NWE5NjViNDEzMSIsInNjb3BlIjoiUk9MRV9VU0VSIDAwMDAifQ.8dcCu3XQI69Ws9sTi6oLMOU0_904ZuwlV1GuHWe7fTUWZrm5jXYV0LmxCjAgQoreZlgO19IiAJPN3jKItD7ndA

GET {{url}}?search=%C3%A1
Authorization: {{token}}

###
GET {{url}}/6829a1ecd0200ef461827996
Authorization: {{token}}

###
DELETE {{url}}/682c9e9366f4f38be94064ba
Content-Type: application/json
Authorization: {{token}}

{
  "shopId": "78ae67b6-da49-4722-99ba-43dbb67946a8"
}

### 
PUT {{url}}/682c1ca659a560ed176c2575
Content-Type: application/json
Authorization: {{token}}

{
  "name": "Mũ trẻ em",
  "shopId": "78ae67b6-da49-4722-99ba-43dbb67946a8",
  "description": "Chiếc mũ bảo hộ hình ếch siêu dễ thương dành cho các bé yêu! 🐸\n\nThiết kế ngộ nghĩnh với hình mặt ếch đáng yêu, cùng với kính chắn trong suốt, bảo vệ bé khỏi khói bụi, giọt bắn và ánh nắng mặt trời.\n\nMũ có nhiều màu sắc tươi sáng để lựa chọn, phù hợp với sở thích của từng bé.\n\nVừa bảo vệ an toàn, vừa làm điệu cho bé yêu, còn chần chừ gì mà không sắm ngay! 🤩",
  "price": 25000,
  "category": "BooksStationery",
  "attribute": {
    "brand": "Thiên Long",
    "category": "Sách",
    "genre": "Sách",
    "author": "John Doe"
  },
  "images": [
    "g18_ecommerce/ya6bnyz72hzw2yn85plc",
    "g18_ecommerce/u8hwntlas62hpgmqbgpi",
    "g18_ecommerce/xbhjfro1vh83jc3qcrgh"
  ],
  "thumbnailImage": "g18_ecommerce/trrhsuur40llohalxxjo",
  "ratings": {
    "average": 0,
    "count": 0
  },
  "isActive": false,
  "tags": [
    "sach",
    "hocsinh"
  ],
  "createdAt": {
    "$date": "2025-05-20T06:09:42.503Z"
  },
  "updatedAt": {
    "$date": "2025-05-20T15:30:49.174Z"
  },
  "__v": 0
}
