@url=http://localhost:5000

### Create inventory
POST {{url}}/api/inventories/
Content-Type: application/json

{
    "shop_id": "shop_001",
    "product_name": "Frozen Granite Hat",
    "product_id": "681794a4c6921cdcd68b26e8",
    "total_quantity": 100
}