name: Deploy Selected Services

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ProductService/**'
      - 'DiscountService/**'
      - 'InventoryService/**'

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      product_changed: ${{ steps.product.outputs.changed }}
      discount_changed: ${{ steps.discount.outputs.changed }}
      inventory_changed: ${{ steps.inventory.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # cần để git diff so sánh với origin/main

      - id: product
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^ProductService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - id: discount
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^DiscountService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      - id: inventory
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^InventoryService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
  deploy-product-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.product_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_MINH }}" | docker login -u "${{ secrets.DOCKER_USERNAME_MINH }}" --password-stdin
      - name: Build & Push ProductService image
        run: |
          docker build -f ProductService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_MINH }}/product-service:latest ProductService
          docker push ${{ secrets.DOCKER_USERNAME_MINH }}/product-service:latest
      - name: Trigger Render Redeploy (ProductService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_PRODUCT }}

  deploy-discount-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.discount_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_VU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_VU }}" --password-stdin
      - name: Build & Push DiscountService image
        run: |
          docker build -f DiscountService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_VU }}/discount-service:lastest DiscountService
          docker push ${{ secrets.DOCKER_USERNAME_VU }}/discount-service:lastest
      - name: Trigger Render Redeploy (DiscountService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_DISCOUNT }}

  deploy-inventory-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.inventory_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_VU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_VU }}" --password-stdin
      - name: Build & Push InventoryService image
        run: |
          docker build -f InventoryService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_VU }}/inventory-service:lastest InventoryService
          docker push ${{ secrets.DOCKER_USERNAME_VU }}/inventory-service:lastest
      - name: Trigger Render Redeploy (InventoryService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_INVENTORY }}
