name: Deploy Selected Services

on:
  push:
    branches:
      - main
    paths:
      - 'ProfileService/**'
      - 'IdentifyService/**'

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      profile_changed: ${{ steps.profile.outputs.changed }}
      identify_changed: ${{ steps.identify.outputs.changed }}
    steps:
      - uses: actions/checkout@v3

      - id: profile
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^ProfileService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - id: identify
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q '^IdentifyService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
  deploy-profile-service:
    runs-on: ubuntu-latest
    if: needs.check-paths.outputs.profile_changed == 'true'
    needs: check-paths
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_HIEU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_HIEU }}" --password-stdin

      - name: Build & Push ProfileService image
        run: |
          docker build -f ProfileService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_HIEU }}/profileservice:latest ProfileService
          docker push ${{ secrets.DOCKER_USERNAME_HIEU }}/profileservice:latest

      - name: Trigger Render Redeploy (ProfileService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_PROFILE }}

  deploy-identify-service:
    runs-on: ubuntu-latest
    if: needs.check-paths.outputs.profile_changed == 'true'
    needs: check-paths
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_HIEU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_HIEU }}" --password-stdin

      - name: Build & Push IdentifyService image
        run: |
          docker build -f IdentifyService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_HIEU }}/identifyservice:latest IdentifyService
          docker push ${{ secrets.DOCKER_USERNAME_HIEU }}/identifyservice:latest

      - name: Trigger Render Redeploy (IdentifyService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_IDENTIFY }}
