name: Deploy Selected Services

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ProfileService/**'
      - 'IdentifyService/**'
      - 'OrderService/**'
      - 'PaymentService/**'
      - 'BasketService/**'

jobs:
  check-paths:
    runs-on: ubuntu-latest
    outputs:
      profile_changed: ${{ steps.profile.outputs.changed }}
      identify_changed: ${{ steps.identify.outputs.changed }}
      order_changed: ${{ steps.order.outputs.changed }}
      payment_changed: ${{ steps.payment.outputs.changed }}
      basket_changed: ${{ steps.basket.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - id: profile
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^ProfileService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - id: identify
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^IdentifyService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - id: order
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^OrderService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - id: payment
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^PaymentService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - id: basket
        run: |
          if git diff --name-only origin/main...HEAD | grep -q '^BasketService/'; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
  deploy-profile-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.profile_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_HIEU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_HIEU }}" --password-stdin
      - name: Build & Push ProfileService image
        run: |
          docker build -f ProfileService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_HIEU }}/profileservice:latest ProfileService
          docker push ${{ secrets.DOCKER_USERNAME_HIEU }}/profileservice:latest
      - name: Trigger Render Redeploy (ProfileService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_PROFILE }}

  deploy-identify-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.identify_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_HIEU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_HIEU }}" --password-stdin
      - name: Build & Push IdentifyService image
        run: |
          docker build -f IdentifyService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_HIEU }}/identifyservice:latest IdentifyService
          docker push ${{ secrets.DOCKER_USERNAME_HIEU }}/identifyservice:latest
      - name: Trigger Render Redeploy (IdentifyService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_IDENTIFY }}

  deploy-order-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.order_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_VU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_VU }}" --password-stdin
      - name: Build & Push OrderService image
        run: |
          docker build -f OrderService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_VU }}/order-service:lastest OrderService
          docker push ${{ secrets.DOCKER_USERNAME_VU }}/order-service:lastest
      - name: Trigger Render Redeploy (OrderService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_ORDER }}

  deploy-payment-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.payment_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_VU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_VU }}" --password-stdin
      - name: Build & Push PaymentService image
        run: |
          docker build -f PaymentService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_VU }}/payment-service:lastest PaymentService
          docker push ${{ secrets.DOCKER_USERNAME_VU }}/payment-service:lastest
      - name: Trigger Render Redeploy (PaymentService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_PAYMENT }}

  deploy-basket-service:
    runs-on: ubuntu-latest
    needs: check-paths
    if: needs.check-paths.outputs.basket_changed == 'true'
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD_VU }}" | docker login -u "${{ secrets.DOCKER_USERNAME_VU }}" --password-stdin
      - name: Build & Push BasketService image
        run: |
          docker build -f BasketService/Dockerfile -t ${{ secrets.DOCKER_USERNAME_VU }}/basket-service:lastest BasketService
          docker push ${{ secrets.DOCKER_USERNAME_VU }}/basket-service:lastest
      - name: Trigger Render Redeploy (BasketService)
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL_BASKET }}
